# Generated by Django 5.1.1 on 2024-10-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikazioa1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ikasgaiak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('maila', models.CharField(max_length=100)),
                ('hizkuntza', models.CharField(max_length=75)),
            ],
        ),
    ]
