# Generated by Django 5.1.1 on 2024-10-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikazioa1', '0002_ikasgaiak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('oharra', models.CharField(max_length=200)),
                ('Ikasgaiak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplikazioa1.ikasgaiak')),
                ('Ikasle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplikazioa1.ikasle')),
            ],
        ),
    ]
