# Generated by Django 5.1.1 on 2024-10-08 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ibilgailuak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bezeroa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=100)),
                ('abizena', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='kotxea',
            name='alokatua',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AlokatutakoKotxeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alokatze_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('kotxea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ibilgailuak.kotxea')),
                ('bezeroa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ibilgailuak.bezeroa')),
            ],
        ),
    ]
